### ISSUE TITLE
withHTML global decorator seems to conflict with the storyshots addon

### ISSUE THREAD

**Issue by KevinVandy** [whitespace-se/storybook-addon-html#5] opened 2020-01-19 18:11 UTC
I only just recently added this html addon to our storybook. It works great, but with the decorator enabled, all of our storybook snapshots throw runtime errors. Can't even update the snapshots. 

Running
`yarn test`
will produce this on each of the storyshots.
```
● Storyshots › Components/Atoms/Buttons › Primary Button

    TypeError: Cannot read property 'innerHTML' of null

      at node_modules/@whitespace/storybook-addon-html/lib/decorators/react.js:35:32
      at commitHookEffectList (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12145:26)
      at commitPassiveHookEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12179:11)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11758:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11807:16)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11860:31)
      at flushPassiveEffectsImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15402:7)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:697:12)
      at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2013:10)
      at flushPassiveEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15371:12)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14361:5)
      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2063:24
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:697:12)
      at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2013:10)
      at flushSyncCallbackQueueImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2058:7)
      at flushSyncCallbackQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2046:3)
      at scheduleUpdateOnFiber (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13819:9)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:17037:3)
      at create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:17777:5)
      at getRenderedTree (node_modules/@storybook/addon-storyshots/dist/frameworks/react/renderTree.js:23:16)
      at node_modules/@storybook/addon-storyshots/dist/test-bodies.js:10:22
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/api/snapshotsTestsTemplate.js:42:20)
   ...
```
My workaround is to just comment out 
`addDecorator(withHTML());`
in my config.js whenever I need to test the snapshots, and that works fine, so this is not that much of a deal breaker.

**Comment by nguyenvantruong17** [comment] 2020-07-28 04:21
@KevinVandy I got same issue. Have you fixed it?

**Comment by jeanfredrik** [comment] 2020-08-06 17:28
@KevinVandy Did you figure this out on your own? If not, could you try upgrading to 1.2.4. I could not reproduce the exact error you had, but got another one that I fixed. If it’s still not working, please tell me what version of Storybook and Jest you are using and provide a code example of a story file as well as your main.js and preview.js files.

**Comment by jeanfredrik** [comment] 2020-09-09 12:23
I’m closing this now. Feel free to re-open if this is still a relevant issue.

**Closed by jeanfredrik** 2020-09-09 12:23 UTC
Labels: bug

**Comment by nguyenvantruong17** [comment] 2020-09-13 10:47
It seems like there is no need to update the snapshot with jest.
This is my config and it work well
```tsx
if (process.env.NODE_ENV !== 'test') {
  addDecorator(
    withHTML()
  );
}
```
