### ISSUE TITLE
 Uncaught TypeError with Storybook 7 / Vite

### ISSUE THREAD

**Issue by jeffpreussner** [whitespace-se/storybook-addon-html#99] opened 2023-06-07 16:48 UTC
Getting a TypeError that prevents Storybook from loading.

Relevant package versions:
- "@vitejs/plugin-react": "^1.3.0",
- "@whitespace/storybook-addon-html": "^5.1.5",
- "@storybook/addon-a11y": "^7.0.18",
- "@storybook/addon-essentials": "^7.0.18",
- "@storybook/addon-links": "^7.0.18",
- "@storybook/manager-api": "^7.0.18",
- "@storybook/react": "^7.0.18",
- "@storybook/react-vite": "^7.0.18",
- "@storybook/test-runner": "0.10.0",
- "@storybook/theming": "^7.0.18",
- "vite": "^4.3.9",
- "storybook": "^7.0.18",

`
Panel.js:12 Uncaught TypeError: import_addons.addons.register is not a function at Panel.js:12:51
(anonymous) @ Panel.js:12
Show 1 more frame
`

**Comment by j0k3r** [comment] 2023-06-08 07:01
Same here:
> ERR! Error: [vite]: Rollup failed to resolve import "@storybook/api" from "/home/travis/build/.../node_modules/@whitespace/storybook-addon-html/dist/esm/Panel.js".

**Comment by dryton** [comment] 2023-06-08 09:25
It looks like Storybook 7 uses "@storybook/manager-api" for the Storybook hooks now:
https://storybook.js.org/docs/react/addons/addons-api#storybook-hooks

**Comment by JackofD** [comment] 2023-06-08 13:26
Just bumping this, as I'm having what looks like the same issues as the original poster.
I'm using Storybook 7 with Vue and Vite.

This shows up in the terminal after running storybook:
`WARN You (or an addon) are using the 'config' preset field. This has been replaced by 'previewAnnotations' and will be removed in 8.0`

And this is the error in the browser/console:
`TypeError: import_addons.addons.register is not a function
    at http://localhost:6006/node_modules/.cache/.vite-storybook/deps/@whitespace_storybook-addon-html_dist_esm_preset_manager__js.js?v=cc2a5e99:25187:22`

If I take out the HTML addon from the addons array in main.js - things run as per normal.

My package.json - relevant packages
```
"devDependencies": {
    "@storybook/addon-essentials": "^7.0.20",
    "@storybook/addon-interactions": "^7.0.20",
    "@storybook/addon-links": "^7.0.20",
    "@storybook/addon-mdx-gfm": "^7.0.20",
    "@storybook/blocks": "^7.0.20",
    "@storybook/testing-library": "^0.1.0",
    "@storybook/vue3": "^7.0.20",
    "@storybook/vue3-vite": "^7.0.20",
    "@vitejs/plugin-vue": "^4.2.3",
    "@vue/test-utils": "^2.3.2",
    "@whitespace/storybook-addon-html": "^5.1.5",
    "jsdom": "^22.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "storybook": "^7.0.20",
    "vite": "^4.3.5",
    "vitest": "^0.31.0"
  }
```

Hoping we have a solve for this.

**Comment by jaylaw81** [comment] 2023-06-08 15:19
Having the same issue as well. In regards to the addon

```
TypeError: addons.register is not a function
```

**Comment by Koda-Pig** [comment] 2023-06-09 09:29
Bumping, getting the same error.

**Comment by okamoai** [comment] 2023-06-10 06:05
https://github.com/whitespace-se/storybook-addon-html/blob/02d6dacf233f627de0322cc16bae5539fe505541/preset.js#L9-L11

Calling './dist/esm/preset/manager' in previewAnnotations, but isn't it supposed to be './dist/esm/preset/preview'?
When I tried correcting this in my own environment, I confirmed that the error was resolved.

**Comment by jeanfredrik** [comment] 2023-06-13 17:19
I've merged #100 and published v5.1.6. Does upgrading to that version solve this issue?

**Comment by j0k3r** [comment] 2023-06-14 04:03
@jeanfredrik yes fixed, thanks!

**Closed** 2023-06-14 09:29 UTC

**Comment by josh-bluegrass** [comment] 2023-06-15 07:07
Thanks so much @jeanfredrik!
