### ISSUE TITLE
Expecting an HTML snippet or DOM node from the story message with Storybook Vue

### ISSUE THREAD

**Issue by kimchristiansen** [whitespace-se/storybook-addon-html#60] opened 2021-12-13 08:30 UTC
If i use the storybook-addon-html in a @storybook/vue i get the following message on each story:

```
Expecting an HTML snippet or DOM node from the story: "Primary" of "Example/Heading".
Did you forget to return the HTML snippet from the story?
Use "() => <your snippet or node>" or when defining the story.
```
I use the default @storybook/vue 6.4.9 with vue 2.6.11 and @whitespace/storybook-addon-html 5.0.0

A simplified story look like this, and throws the error:

```
export const Heading = () => ({
  components: { MyHeading },
  template: '<h1>Heading Test</h1>',
});
```

If i remove the vue template and rewrite the story to this static return, the error disappears and the html output is working:

`export const H1 = () => ('<h1>Heading Test</h1>'); `

Did i miss something?

**Comment by jeanfredrik** [comment] 2022-09-27 08:05
Did you resolve this issue? I'm not actively using Vue so I don't see exactly what the issue is about. Happy to get some help

**Comment by kimchristiansen** [comment] 2022-09-27 08:22
No, i sadly did not resolve the issue and used an other storybook.

**Comment by jeanfredrik** [comment] 2022-11-14 15:10
Let me know if this is still an issue after upgrading to version 5 of the addon. I will close this for now.

**Closed by jeanfredrik** 2022-11-14 15:10 UTC
Labels: bug, help wanted
